apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  annotations:
    external-dns.alpha.kubernetes.io/hostname: docker-registry.public.kube.usatxaus.lab
  labels:
    k8s-app: kube-registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: kube-registry
  ports:
  - name: registry
    port: 80
    protocol: TCP
    targetPort: 5000
  type: LoadBalancer
